### ISSUE TITLE
Análisis Exploratorio de Datos(EDA).

### ISSUE THREAD

**Issue by BeaDataArtist** [laural87/project-da-promo-I-modulo-3-team-2#1]

**Comment by 910129023** [comment]
Descripción del análisis de Datos que hemos hecho

- [x] Crear las conclusiones del EDA 
- [x] Exploración previa del DF
- [x] Distribución de nulos 
- [x] Verificado el tipo de datos y valores.
- [x] Verificamos que no hay duplicados.
